<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -g -gl -vewnhi -l -Fu/usr/lib/lazarus/1.0.10/packager/units/%(CPU_TARGET)-%(OS_TARGET);. laz_synapse.pas"/>
</CONFIG>
